python_distribution(
    name="xlvs-pants2",
    dependencies=[
        "//src/xlvs/pants/docker",
    ],
    provides=setup_py(
        name="xlvs-pants2",
        version="1.0.0",
        description="Pants2 plugins",
    ),
    setup_py_commands=["bdist_wheel"],
)