on: [push]
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Bootstrap
      run: './pants --version'

    - name: Lint
      run: './pants lint ::'

    - name: Build
      # if:  ${{ github.ref == 'refs/heads/main' }}
      run: './pants package ::'

    - name: Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          - ...
        draft: true
        prerelease: true
    

 